<?php
/**
 * Helper for create a invoice.
 *
 * @author     Alessio Catania
 * @since      1.0.7
 * @package    Wubtitle\Utils
 */

namespace Wubtitle\Utils;

/**
 * Vimeo Helpers
 *
 * @SuppressWarnings(PHPMD.ExcessiveMethodLength)
 */
class VimeoHelper {
	/**
	 * Return languages array.
	 *
	 * @return array<string>
	 */
	public function get_languages() {
		$languages = array(
			'af'    => __( 'Afrikaans', 'wubtitle' ),
			'sq'    => __( 'Albanian', 'wubtitle' ),
			'ar-ae' => __( 'Arabic (U.A.E.)', 'wubtitle' ),
			'ar-bh' => __( 'Arabic (Bahrain)', 'wubtitle' ),
			'ar-dz' => __( 'Arabic (Algeria)', 'wubtitle' ),
			'ar-eg' => __( 'Arabic (Egypt)', 'wubtitle' ),
			'ar-iq' => __( 'Arabic (Iraq)', 'wubtitle' ),
			'ar-jo' => __( 'Arabic (Jordan)', 'wubtitle' ),
			'ar-kw' => __( 'Arabic (Kuwait)', 'wubtitle' ),
			'ar-lb' => __( 'Arabic (Lebanon)', 'wubtitle' ),
			'ar-ly' => __( 'Arabic (Libya)', 'wubtitle' ),
			'ar-ma' => __( 'Arabic (Morocco)', 'wubtitle' ),
			'ar-om' => __( 'Arabic (Oman)', 'wubtitle' ),
			'ar-qa' => __( 'Arabic (Qatar)', 'wubtitle' ),
			'ar-sa' => __( 'Arabic (Saudi Arabia)', 'wubtitle' ),
			'ar-sy' => __( 'Arabic (Syria)', 'wubtitle' ),
			'ar-tn' => __( 'Arabic (Tunisia)', 'wubtitle' ),
			'ar-ye' => __( 'Arabic (Yemen)', 'wubtitle' ),
			'eu'    => __( 'Basque', 'wubtitle' ),
			'be'    => __( 'Belarusian', 'wubtitle' ),
			'bg'    => __( 'Bulgarian', 'wubtitle' ),
			'ca'    => __( 'Catalan', 'wubtitle' ),
			'hr'    => __( 'Croatian', 'wubtitle' ),
			'zh-cn' => __( 'Chinese (PRC)', 'wubtitle' ),
			'zh-hk' => __( 'Chinese (Hong Kong)', 'wubtitle' ),
			'zh-sg' => __( 'Chinese (Singapore)', 'wubtitle' ),
			'zh-tw' => __( 'Chinese (Taiwan)', 'wubtitle' ),
			'cs'    => __( 'Czech', 'wubtitle' ),
			'da'    => __( 'Danish', 'wubtitle' ),
			'nl'    => __( 'Dutch (Standard)', 'wubtitle' ),
			'nl-be' => __( 'Dutch (Belgium)', 'wubtitle' ),
			'en'    => __( 'English', 'wubtitle' ),
			'en-au' => __( 'English (Australia)', 'wubtitle' ),
			'en-bz' => __( 'English (Belize)', 'wubtitle' ),
			'en-ca' => __( 'English (Canada)', 'wubtitle' ),
			'en-gb' => __( 'English (United Kingdom)', 'wubtitle' ),
			'en-ie' => __( 'English (Ireland)', 'wubtitle' ),
			'en-jm' => __( 'English (Jamaica)', 'wubtitle' ),
			'en-nz' => __( 'English (New Zealand)', 'wubtitle' ),
			'en-tt' => __( 'English (Trinidad)', 'wubtitle' ),
			'en-us' => __( 'English (United States)', 'wubtitle' ),
			'en-za' => __( 'English (South Africa)', 'wubtitle' ),
			'et'    => __( 'Estonian', 'wubtitle' ),
			'fa'    => __( 'Farsi', 'wubtitle' ),
			'fi'    => __( 'Finnish', 'wubtitle' ),
			'fo'    => __( 'Faeroese', 'wubtitle' ),
			'fr'    => __( 'French (Standard)', 'wubtitle' ),
			'fr-be' => __( 'French (Belgium)', 'wubtitle' ),
			'fr-ca' => __( 'French (Canada)', 'wubtitle' ),
			'fr-ch' => __( 'French (Switzerland)', 'wubtitle' ),
			'fr-lu' => __( 'French (Luxembourg)', 'wubtitle' ),
			'gd'    => __( 'Gaelic (Scotland)', 'wubtitle' ),
			'de'    => __( 'German (Standard)', 'wubtitle' ),
			'de-at' => __( 'German (Austria)', 'wubtitle' ),
			'de-ch' => __( 'German (Switzerland)', 'wubtitle' ),
			'de-li' => __( 'German (Liechtenstein)', 'wubtitle' ),
			'de-lu' => __( 'German (Luxembourg)', 'wubtitle' ),
			'el'    => __( 'Greek', 'wubtitle' ),
			'ga'    => __( 'Irish', 'wubtitle' ),
			'he'    => __( 'Hebrew', 'wubtitle' ),
			'hi'    => __( 'Hindi', 'wubtitle' ),
			'hu'    => __( 'Hungarian', 'wubtitle' ),
			'id'    => __( 'Indonesian', 'wubtitle' ),
			'is'    => __( 'Icelandic', 'wubtitle' ),
			'it'    => __( 'Italian (Standard)', 'wubtitle' ),
			'it-ch' => __( 'Italian (Switzerland)', 'wubtitle' ),
			'ja'    => __( 'Japanese', 'wubtitle' ),
			'ko'    => __( 'Korean (Johab)', 'wubtitle' ),
			'ku'    => __( 'Kurdish', 'wubtitle' ),
			'lt'    => __( 'Lithuanian', 'wubtitle' ),
			'lv'    => __( 'Latvian', 'wubtitle' ),
			'mk'    => __( 'Macedonian (FYROM)', 'wubtitle' ),
			'ml'    => __( 'Malayalam', 'wubtitle' ),
			'ms'    => __( 'Malaysian', 'wubtitle' ),
			'mt'    => __( 'Maltese', 'wubtitle' ),
			'nb'    => __( 'Norwegian (Bokmål)', 'wubtitle' ),
			'nn'    => __( 'Norwegian (Nynorsk)', 'wubtitle' ),
			'no'    => __( 'Norwegian', 'wubtitle' ),
			'pa'    => __( 'Punjabi', 'wubtitle' ),
			'pl'    => __( 'Polish', 'wubtitle' ),
			'pt'    => __( 'Portuguese (Portugal)', 'wubtitle' ),
			'pt-br' => __( 'Portuguese (Brazil)', 'wubtitle' ),
			'rm'    => __( 'Rhaeto-Romanic', 'wubtitle' ),
			'ro'    => __( 'Romanian', 'wubtitle' ),
			'ro-md' => __( 'Romanian (Republic of Moldova)', 'wubtitle' ),
			'ru'    => __( 'Russian', 'wubtitle' ),
			'ru-md' => __( 'Russian (Republic of Moldova)', 'wubtitle' ),
			'sb'    => __( 'Sorbian', 'wubtitle' ),
			'sk'    => __( 'Slovak', 'wubtitle' ),
			'sl'    => __( 'Slovenian', 'wubtitle' ),
			'sr'    => __( 'Serbian', 'wubtitle' ),
			'es'    => __( 'Spanish (Spain)', 'wubtitle' ),
			'es-ar' => __( 'Spanish (Argentina)', 'wubtitle' ),
			'es-bo' => __( 'Spanish (Bolivia)', 'wubtitle' ),
			'es-cl' => __( 'Spanish (Chile)', 'wubtitle' ),
			'es-co' => __( 'Spanish (Colombia)', 'wubtitle' ),
			'es-cr' => __( 'Spanish (Costa Rica)', 'wubtitle' ),
			'es-do' => __( 'Spanish (Dominican Republic)', 'wubtitle' ),
			'es-ec' => __( 'Spanish (Ecuador)', 'wubtitle' ),
			'es-gt' => __( 'Spanish (Guatemala)', 'wubtitle' ),
			'es-hn' => __( 'Spanish (Honduras)', 'wubtitle' ),
			'es-mx' => __( 'Spanish (Mexico)', 'wubtitle' ),
			'es-ni' => __( 'Spanish (Nicaragua)', 'wubtitle' ),
			'es-pa' => __( 'Spanish (Panama)', 'wubtitle' ),
			'es-pe' => __( 'Spanish (Peru)', 'wubtitle' ),
			'es-pr' => __( 'Spanish (Puerto Rico)', 'wubtitle' ),
			'es-py' => __( 'Spanish (Paraguay)', 'wubtitle' ),
			'es-sv' => __( 'Spanish (El Salvador)', 'wubtitle' ),
			'es-uy' => __( 'Spanish (Uruguay)', 'wubtitle' ),
			'es-ve' => __( 'Spanish (Venezuela)', 'wubtitle' ),
			'sv'    => __( 'Swedish', 'wubtitle' ),
			'sv-fi' => __( 'Swedish (Finland)', 'wubtitle' ),
			'th'    => __( 'Thai', 'wubtitle' ),
			'tn'    => __( 'Tswana', 'wubtitle' ),
			'tr'    => __( 'Turkish', 'wubtitle' ),
			'ts'    => __( 'Tsonga', 'wubtitle' ),
			'uk'    => __( 'Ukrainian', 'wubtitle' ),
			'ur'    => __( 'Urdu', 'wubtitle' ),
			've'    => __( 'Venda', 'wubtitle' ),
			'vi'    => __( 'Vietnamese', 'wubtitle' ),
			'cy'    => __( 'Welsh', 'wubtitle' ),
			'xh'    => __( 'Xhosa', 'wubtitle' ),
			'ji'    => __( 'Yiddish', 'wubtitle' ),
			'zu'    => __( 'Zulu', 'wubtitle' ),
		);
		return $languages;
	}
}
