version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 8.a, < 9"
  - dependency-name: phpunit/phpunit
    versions:
    - ">= 9.a, < 10"
  - dependency-name: szepeviktor/phpstan-wordpress
    versions:
    - 0.7.3
    - 0.7.4
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@wordpress/scripts"
    versions:
    - 13.0.1
    - 13.0.2
    - 13.0.3
    - 14.0.0
    - 14.0.1
    - 14.1.0
  - dependency-name: "@wordpress/i18n"
    versions:
    - 3.17.1
    - 3.18.0
    - 3.19.0
    - 3.19.1
  - dependency-name: "@wordpress/api-fetch"
    versions:
    - 3.21.3
    - 3.21.5
    - 3.22.0
    - 3.23.0
  - dependency-name: "@wordpress/plugins"
    versions:
    - 2.24.3
    - 2.24.5
    - 2.24.6
    - 2.24.7
    - 2.25.0
    - 2.25.1
  - dependency-name: "@stripe/stripe-js"
    versions:
    - 1.12.0
    - 1.12.1
    - 1.13.0
    - 1.13.1
    - 1.13.2
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@stripe/react-stripe-js"
    versions:
    - 1.2.1
    - 1.2.2
    - 1.3.0
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
