variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  MYSQL_DATABASE: wordpress_tests
  MYSQL_ROOT_PASSWORD: mysql

stages:
  - build
  - lint
  - test

cache:
  paths:
    - node_modules/
    - vendor/

PHP7.2-build:
  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
  stage: build
  services:
    - mysql:5.6
  script:
  - composer install
  - npm ci

PHP7.2-lint:
  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
  stage: lint
  services:
    - mysql:5.6
  script:
  - composer check-php

PHP7.2-test:
  image: edbizarro/gitlab-ci-pipeline-php:7.2-alpine
  before_script:
    - sudo apk update
    - sudo apk add subversion
  stage: test
  services:
    - mysql:5.6
  script:
  # Set up WordPress tests
  - bash bin/install-wp-tests.sh wordpress_tests root mysql mysql latest true
  - composer test
