name: Deploy to WordPress.org
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build # Remove or modify this step as needed
      run: |
        composer install --no-dev --prefer-dist --no-interaction
        npm ci --prefer-offline --progress=false
        npm run build
        npm ci --prefer-offline --progress=false --only=prod
        rm -rf src/ tests/ composer.json composer.lock package.json package-lock.json
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: wubtitle
