name: Plugin asset/readme update
on:
  push:
    branches:
    - wordpress.org
jobs:
  trunk:
    name: Push to trunk
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build # Remove or modify this step as needed
      run: |
        composer install --no-dev --prefer-dist --no-interaction
        npm ci --prefer-offline --progress=false
        npm run build
        npm ci --prefer-offline --progress=false --only=prod
        rm -rf src/ tests/ composer.json composer.lock package.json package-lock.json .github .aspell.en.pws .eslintrc.json .gitattributes .stylelintrc.json phpmd.xml phpstan.neon.dist
    - name: WordPress.org plugin asset/readme update
      uses: 10up/action-wordpress-plugin-asset-update@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: wubtitle
